server:
  port: 14564
  servlet:
    context-path: /etcx-obu

# spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.102.1.36:3306/etcx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.wanji.etcxobu.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
logging:
  config: classpath:logback-spring.xml
